# Generated by Django 2.1.10 on 2019-09-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takatarecovery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='makemodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oem', models.TextField(null=True)),
                ('model', models.TextField(null=True)),
                ('note', models.TextField(null=True)),
                ('year', models.TextField(null=True)),
                ('airbag', models.TextField(null=True)),
                ('status', models.TextField(null=True)),
            ],
        ),
    ]
