# Generated by Django 2.1.10 on 2019-09-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takatarecovery', '0002_makemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='takatarecovery',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
