# Generated by Django 2.1.10 on 2019-09-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takatarecovery', '0003_takatarecovery_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takatarecovery',
            name='contact_no',
            field=models.IntegerField(max_length=15, null=True),
        ),
    ]
