# Generated by Django 2.1.10 on 2019-09-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takatarecovery', '0004_auto_20190919_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takatarecovery',
            name='contact_no',
            field=models.IntegerField(null=True),
        ),
    ]
