# Generated by Django 2.1.10 on 2019-09-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takatarecovery', '0006_takatarecovery_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='takatarecovery',
            name='emailMobile',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
