# Generated by Django 2.1.10 on 2019-09-26 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takatarecovery', '0007_takatarecovery_emailmobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takatarecovery',
            name='emailMobile',
        ),
    ]
